### ISSUE TITLE
hello page display not found

### ISSUE THREAD

**Issue by lalop** [smooth-code/smooth.js#50]
I'm using smooth 0.1.1-alpha.61, I try to add an hello page exactely as explained in the Readme but I get a 404.
Can this be the result of a plugin ?

```
Error: Not found
    at Handler (webpack:///./node_modules/smooth/lib/content/Query.js?:67:14)
    at processChild (node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:14)
    at resolve (node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:5)
    at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:22)
    at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
    at renderToStaticMarkup (node_modules/react-dom/cjs/react-dom-server.node.development.js:3969:27)
    at process (node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js:38:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at node_modules/smooth/lib/server/ssr.js:88:5
```

**Comment by lalop** [comment]
It seems that the hello.js file is ignore, it's the index.js file that is loaded

**Comment by lalop** [comment]
If I rename the file `hello$.js` it works.
The issue is closed for me but maybe this could be explained in the documentation
